server:
  port: 8084

logging:
  level:
    root: INFO

okta:
  oauth2:
    issuer: ${OKTA_ISSUER}
    client-secret: ${OKTA_CLIENT_SECRET}
    client-id: ${OKTA_CLIENT_ID}

imgur:
  api:
    client-id: ${IMGUR_CLIENT_ID}
    upload-image-url: https://api.imgur.com/3/image
