server:
  port: 8081

logging:
  level:
    root: INFO

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: findaroom-dev
      auto-index-creation: true

okta:
  oauth2:
    issuer: ${OKTA_ISSUER}
    client-secret: ${OKTA_CLIENT_SECRET}
    client-id: ${OKTA_CLIENT_ID}

paypal:
  secret: ${PAYPAL_SECRET}
  client-id: ${PAYPAL_CLIENT_ID}

